# Generated by Django 4.2.23 on 2025-11-11 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Courses", "0004_merge_20251111_1136"),
        ("Student", "0003_alter_enrollment_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="Courses.course",
            ),
        ),
    ]
