# Generated by Django 4.2.23 on 2025-11-12 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Teacher", "0004_merge_20251111_1135"),
        ("Student", "0004_alter_enrollment_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentsubmission",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="Teacher.teacherassignment",
            ),
        ),
    ]
