# Generated by Django 4.2.23 on 2025-11-12 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Courses", "0004_merge_20251111_1136"),
        ("Teacher", "0006_question_choice"),
        ("Student", "0006_quizsubmission"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Teacher.question",
                    ),
                ),
                (
                    "selected_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Teacher.choice"
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="Student.quizsubmission",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="classsession",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="Courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="Courses.course",
            ),
        ),
        migrations.DeleteModel(
            name="Course",
        ),
    ]
