# Generated by Django 5.2.4 on 2025-11-13 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0005_remove_course_course_image'),
        ('Student', '0007_quizanswer_alter_classsession_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='submitted_on',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_feedbacks', to='Courses.course'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_feedbacks', to='Student.studentprofile'),
        ),
    ]
