# Generated by Django 5.2.4 on 2025-11-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_rename_submitted_on_feedback_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_text',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
        migrations.AddField(
            model_name='feedback',
            name='achieved_objective',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='duration_appropriate',
            field=models.CharField(default='Not answered', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='improvement_suggestions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='material_easy',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='overall_satisfaction_rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='recommend_trainer',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='relevance_rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='trainer_knowledge_rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
