# Generated by Django 4.2.23 on 2025-11-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_image",
            field=models.ImageField(blank=True, null=True, upload_to="course_images/"),
        ),
    ]
