# Generated by Django 5.2.4 on 2025-11-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='more_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
