# Generated by Django 4.2.23 on 2025-11-11 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Courses", "0002_course_course_image"),
        ("Courses", "0003_course_more_info_course_price"),
    ]

    operations = []
