# Generated by Django 5.2.4 on 2025-11-13 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0004_merge_20251111_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_image',
        ),
    ]
