# Generated by Django 4.2.23 on 2025-11-10 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Courses", "0001_initial"),
        ("Teacher", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="Courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="teacherassignment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="Courses.course",
            ),
        ),
    ]
