# Generated by Django 4.2.23 on 2025-11-11 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Teacher", "0002_alter_teacherassignment_course_alter_note_course_and_more"),
        ("Teacher", "0003_quiz"),
    ]

    operations = []
