# Generated by Django 4.2.23 on 2025-11-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Teacher", "0004_merge_20251111_1135"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="end_time",
            field=models.DateTimeField(
                blank=True, help_text="Quiz end date and time", null=True
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="start_time",
            field=models.DateTimeField(
                blank=True, help_text="Quiz start date and time", null=True
            ),
        ),
    ]
