# Generated by Django 4.2.23 on 2025-11-08 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginotp",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 11, 8, 16, 1, 26, 747753, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
